initial structure redis
gopherslab/conduit-connector-redis pull request #1
Opened 2022-04-10 06:06 UTC by aathiraashok

2022-04-12 04:28 UTC, amansardana commented on spec.go
> +			config.ConfigKeyDatabase: {
Is database name a required field, Can we connect to a key without it?

2022-04-13 09:00 UTC, amansardana commented on source/iterator.go
> +func NewCDCIterator(ctx context.Context, client redis.Conn, key string) (*sdk.Record, error) {
This should return an instance of a struct which adheres to the iterator interface and not sdk.Record

2022-04-25 07:47 UTC, amansardana commented on config/config_test.go
> +			if got, _ := Parse(tt.config); !reflect.DeepEqual(got, tt.want) {
Where are we checking the `error`?

2022-04-25 07:47 UTC, amansardana commented on source/iterator.go
> +		psc.Subscribe(key)
Doesn't it return any error?

2022-04-25 07:48 UTC, amansardana commented on source/source.go
> +	// Stop()
Why is it commented out?

2022-04-25 07:54 UTC, amansardana commented on source/source.go
> +	// Stop()
In Stop, close the go routine that we started, in NewCDCIterator

2022-04-25 07:55 UTC, amansardana commented on source/iterator.go
> +	testRecord map[string]sdk.Record
change the name

2022-04-25 07:55 UTC, amansardana commented on source/iterator.go
> +	delete(i.testRecord, i.key)
Will we have only one message in map or multiple?

2022-04-28 05:32 UTC, viknesh-nm requested changes

2022-04-28 05:32 UTC, viknesh-nm commented on source/iterator.go
> +		for {
for should be in default.

2022-04-28 05:32 UTC, viknesh-nm commented on source/iterator.go
> +				// c := map[string]sdk.Record{
remove, if its not necessary

2022-04-28 05:32 UTC, viknesh-nm commented on source/iterator.go
> +	errs := make(chan error)
make the channel as buffered to `make(chan error, 1)`

2022-05-09 17:37 UTC, closed without merging